language: python
python: "3.10"

services:
  - docker

before_install:
  - docker-compose up -d db  # Levanta solo MySQL
  - sleep 20  # Espera inicial para MySQL

install:
  - docker-compose build web  # Construye la imagen de Flask

script:
  # Verifica que MySQL esté listo
  - docker-compose exec db mysqladmin ping -h localhost --silent || exit 1
  
  # Ejecuta pruebas (ajustar según tu estructura)
  - docker-compose run web python -m pytest tests/
  
  # Health check básico
  - docker-compose run web flask check

after_script:
  - docker-compose down  # Limpieza
  