services:
  web:
    build: .
    command: ["./wait-for-db.sh", "python", "main.py"]
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:5000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  jenkins:
    image: proyecto-docker-jenkins
    container_name: proyecto-docker-jenkins-1
    user: "0:1000"             # ⬅️ Ejecuta Jenkins como root pero con GID=1000 (docker)
    group_add:
      - "1000"                 # ⬅️ Añade el grupo docker dentro del contenedor
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
