services:
  jenkins:
    image: proyecto-docker-jenkins
    container_name: proyecto-docker-jenkins-1
    user: "0:1000"
    group_add:
      - "1000"
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: