name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost --silent"
          --health-interval 5s
          --health-retries 10
          --health-timeout 10s

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Compose
        run: docker compose build

      - name: Run Tests
        run: docker compose run web pytest tests